### ISSUE TITLE
Issue to trigger releases

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBase.jl#345]

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

#518

**Comment by ablaom** [comment]
@JuliaRegistrator register

#519 

Release notes:

- [x] (**enhancement**) Allow user to specify `class _weights=...` in `evaluate/evaluate!`, just as she already can pass `weights`. This will pass the class weights to measures that support them. These include: `MulticlassFScore`, `MulticlassFalseDiscoveryRate`, `MulticlassFalseNegativeRate`, `MulticlassFalsePositiveRate`, `MulticlassNegativePredictiveValue`, `MulticlassPrecision`, `MulticlassTrueNegativeRate`, and `MulticlassTruePositiveRate` (#515 @ven-k @ablaom)

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

#521

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- [x] Add support for iterative models (#523, https://github.com/alan-turing-institute/MLJ.jl/issues/139)

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- [x] (**breaking**) Remove OpenML integration, now provided by [MLJOpenML](https://github.com/JuliaAI/MLJOpenML.jl)

- [x] (**breaking**) Remove functionality for saving and retrieving machines, now provided by [MLJSerialization](https://github.com/JuliaAI/MLJSerialization.jl)

**Comment by ablaom** [comment]
@giordano I'll register the new packages after this is merged. 

Thanks again for the great work.

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- [x] Suppress `P <: Real` check for the type of probabilities in `UnivariateFinite`. Allow `UnivariateFinite` objects to be unnormalised (ie, represent arbitrary signed measures on their discrete support). In this way also allow "probabilities" of `NaN`, `Inf`, or `-Inf`, to address #525 (PR #531)
- [x] Extend compatibility requirements to support MLJModelInterface 1.0 and StatisticalTraits 1.0 (which are essentially identical to previous versions)

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- update compatibility for PrettyTables (1.0) and Missings (1.0)

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- [x] Make the `show` method, and `fitted_params`/`report` for composite models property-based, instead of field-based (#553 )

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- [x] Fix bug with `Resampler` (#559)
- [x] Add `train_test_rows` field to performance evaluation objects (#559)
- [x] Improve error message for attempts to call `report/fitted_params` on an untrained machine (#558)

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- [x] (**ehnancement**) Add canned version of Wolpert model stacking, `Stack` (#564) @olivierlabayle @ablaom
- [x] (**bug fix**) Fix overflow bug in `MatthewsCorrelation` coefficient (#571) @giordano
- [x] (**enhancement**) Overload `partition` to work on arbitrary vectors, matrices and tables (#361) @giordano 
- [x] (**bug fix**) Fix flawed interface point for RNG specification in synthetic data methods, such as `make_blobs` (#567) @OkonSamuel 
- [x] Remove LossFunctions.jl type piracy (#577) @ablaom

**Comment by ablaom** [comment]
cc @olivierlabayle

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] (**enhancent**) Add `CVTimeSeries` resampling strategy, for time series data (#331) @aa25desh @CameronBieganek

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

- [x] Improve performance of `nrows` for row-based tables (#591) @OkonSamuel

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=mastert

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] (**enhancement**) Extend `Finite` measures to accept `missing` values (#618)
- [x] (**enhancement**) In cases of a probabilistic model, have `evaluate!` automatically choose the operation (`predict_mode`, `predict_mean`, etc) when user specifies a *deterministic* measure. Allow a mixture of deterministic and probabilistic measures to be specified for such models. Allow automatic behaviour to be explicitly overridden by specifying a *vector* `operations=...`. This mitigates a common gotcha for new users (#598, #599, #600)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] (**enhancement**)  Integrate new outlier detection types added to MLJModelInterface (https://github.com/alan-turing-institute/MLJ.jl/issues/780, https://github.com/JuliaAI/MLJModelInterface.jl/pull/113) and adapt performance evaluation methods to handle them (#628)

Relating to measures: 

- [x] (**enhancement**) Measures: Add `SphericalScore` and `LogScore` (negative of `LogLoss`). 
- [x] (**enhancement**) Extend  the proper scoring rules `SphericalScore`, `LogScore` and `BrierScore` to handle `Continuous` and `Count` data. Supported distributions types from `Distributions` are: `Uniform`, `Normal`, `Exponential`, `Logistic`, `Chi`, `Chisq`, `Beta`, `Gamma`, `Cauchy`, `Poisson`, `DiscreteUniform`, `DiscreteNonParameteric` (#627)
- [x] (**enhancement**) Add `missing` and `NaN` support for all measures, excluding `AreaUnderCurve` and measures from LossFunctions.jl (which imported library does not support) (#616)
- [x] (**enhancement**) Add `skipinvalid(y)` and `skipinvalid(yhat, y)` methods. The first returns an iterator that skips `missing` and `NaN` values - similar to `skipmissing` and is performant. The second returns the flattened forms of `yhat` and `y` with invalid entries removed "commensurately" from both `yhat` and `y`, meaning an element of either argument is skipped *even if valid*, if the corresponding element of the other argument *is* invalid (#627). This method is necessarily less efficient and provided for convenience for pre-processing data for the measures which do not support invalid entries (#627, #616)
- [x] (**enhancement**) Allow most measures for `Finite` data to be called with "raw" data, that is, data that is not wrapped as `CategoricalArray`. This includes `ConfusionMatrix`. A warning is issued to indicate order ambiguity, with the usual suggestion to coerce to `OrderedFactor` to suppress the warning (#627)
- [x] (**enhancement**) Allow measures to be called on arrays, and not just vectors (#627) but see remaining limitations at #631.
- [x] (**API**) Make implementing new measures simpler (#627) and less error-prone. See [this guide](https://github.com/JuliaAI/MLJBase.jl/blob/dev/src/measures/README.md) for details.
- [x] (**enhancement**) Introduce new method `MLJBase.call(measure, args...)` to call a measure without applying dimension or pool checks.
- [x] (**bug fix**) Prevent weights passed to measures from Loss functions.jl from being normalized (#626)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [ ] (**bug fix**) Correct bug in `MulticlassTrueNegative` (#629)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] Fix bug with classification metrics exposed by Julia 1.6.3 release (#646) @OkonSamuel 
- [x] Remove some corner cases of `NaN` in `MulticlassFScore` that are resolved by eliminating common `TP` factor in defining quotient (#637) @OkonSamuel

**Comment by ablaom** [comment]
@pazzo83

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- [x] Fix bug with classification metrics exposed by Julia 1.6.3 release (#646) @OkonSamuel 
- [x] Remove some corner cases of `NaN` in `MulticlassFScore` that are resolved by eliminating common `TP` factor in defining quotient (#637) @OkonSamuel

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- Generalize `FScore` so as to handle some corner cases (#650) 
- Add `adjusted` option to `BalancedAccuracy` (#569)
- Make some improvements to `show` methods (#532, #654, #273)
- Allow `predict_mode` to work with `Unsupervised` models (#658)
- Fix input checks for `UnsupervisedAnnotator` (and so for unsupervised outlier detector models) (#657)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- Fix the `orientation` trait of `RSquared` (#684) 
- Fix a bug in `from_network_preprocess` responsible for `@pipeline` not working outside of `Main` (#685)  @Pangoraw

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- (**enhancement**) Add a new `Pipeline` type for constructing pipelines without macros. Pipelines are to be constructed using the syntax `model1 |> model2 |> ...` or with the constructor `Pipeline` which exposes more options. The `@pipeline` macro is deprecated (#664)
- (**enhancement**) Add the metamodel `TransformedTargetModel` for wrapping supervised models in transformations of the target variable, which can be *learned* transformations (eg, standardisation). Previously this functionality was available as part of `@pipeline` (#678)
- (**breaking**) The `|>` syntax is no longer available for creating learning networks as it is now reserved for pipeline creation and concatenation. Also, `model |> f` has a new meaning when `model` is a `Model` subtype or instance. Previously, it meant `f(model)`, but now it is syntactic sugar for `Pipeline(model, f)` (#664)
- (**breaking**) The `UnivariateFinite` distribution and constructor, and the `UnivariateFiniteArray` type, are no longer available, as they are now provided by a separate package [CategoricalDistributions.jl](https://github.com/JuliaAI/CategoricalDistributions.jl) (which includes generalization to signed and complex measures, and a better display) (#688)
- (**breaking**) `schema(X)` no longer includes the `nrows` property. Use `nrows(X)` instead. This follows from [changes](https://github.com/JuliaAI/ScientificTypes.jl/releases/tag/v3.0.0) in the dependency ScientificTypes.jl (#698)
- Progress meters are no longer displayed for processes concluding in 0.1 s or less (#698)
- (**mildly breaking**) To improve robustness, the `range(model, :hyperparameter, ...)` constructor now tries to infer type information for the range from the corresponding fieldtype for field `:hyperparameter`, rather than from the type of the current *value*. Fix a bug with the display. (#666)
- (**mildly breaking**) `unpack(table, p1, p2, ...)` now includes an extra component in its return value, namely a table with all columns not selected by any of the predicates `p1, p2, ... ` Generally existing code will just safely ignore the extra component (#691)
- (**breaking**) Because more plotting algorithms support it, the default `scale` for unbounded `NumericRange`s is changed from `:log` to `:log10` (#677). 
- (**breaking**) Remove deprecated code for exporting learning networks by hand (#643), which is now achieved using `return!` method ([docs](https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/#Method-II:-Finer-control-(advanced))). 
- (**enhancement**) The `partition` function can now be called with a tuple of data arguments, for "synchronised" partitioning, but this requires specifying `multi=true` (because some tables are tuples) as in `(Xtrain, ytrain), (Xtest, ytest) = partition((X, y), rng=123, multi=true)` #696
- (**mildly breaking**) Make the objects returned by `evaluate/evaluate!` into a `struct` (formerly a named tuple) and add informative doc-string (#697)
- (**enhancement**) Create a way to include the state, after training, of arbitrary nodes of a learning network, in the report of a model created by exporting the learning network (#644)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
cc @OkonSamuel

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- overload the `target_scitype` trait to give sensible value for the `Stack` model type (#711) @olivierlabayle

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

release notes:

- Drop support for julia < 1.6
- Add doc strings to built-in measure instances #719 
- Programatically re-export all measure types, aliases and instances #720

**Comment by ablaom** [comment]
@JuliaRegistrator register branch = master

release notes:

- (**enhancement**) Add cross-validation scores for `Stack` base learners to the training report based on user-specified `measures` (#712) @olivierlabayle

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

-  (**enhancement**) Add Cohen's kappa, `Kappa` (#738) @Rahulub3r

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Remove the restriction on resampling strategies for `Stack` requiring `nfolds` to be a field (#745) @olivierlabayle

**Comment by ablaom** [comment]
Release notes:

- Relax and simplify scitype checks when constructing machines. The existing `fit_data_scitype` model trait encodes all allowed `fit` "scitype" signatures, and scitype checks now only consider this trait. In particular, an appropriately implemented transformer can now be passed  a training target without tripping the type checker. (#699, #732) @pazzo83 @ablaom 
- (**enhancement**, **breaking**) Redesign the serialization API to: (i) Allow use of arbitrary serialization packages for core serialization; (ii) Ensure serialization plays nicely with model composition and meta-algorithms like tuning; (iii) Ensure all traces of training data are absent in serialised models (not previously true for all composite models or if `cache=true` in machine constructor). Models with non-persistent learned parameters (`fitresult`) implement a modified model API that is documented [here](https://github.com/alan-turing-institute/MLJ.jl/blob/serialization-docs/docs/src/adding_models_for_general_use.md#serialization). The new user workflow will shortly appear in the [MLJ manual](https://alan-turing-institute.github.io/MLJ.jl/dev/) under "Machines". (https://github.com/JuliaAI/MLJSerialization.jl/issues/15, #733, https://github.com/JuliaAI/MLJSerialization.jl/issues/16) @olivierlabayle

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Relax and simplify scitype checks when constructing machines. The existing `fit_data_scitype` model trait encodes all allowed `fit` "scitype" signatures, and scitype checks now only consider this trait. In particular, an appropriately implemented transformer can now be passed  a training target without tripping the type checker. (#699, #732) @pazzo83 @ablaom 
- (**enhancement**, **breaking**) Redesign the serialization API to: (i) Allow use of arbitrary serialization packages for core serialization; (ii) Ensure serialization plays nicely with model composition and meta-algorithms like tuning; (iii) Ensure all traces of training data are absent in serialised models (not previously true for all composite models or if `cache=true` in machine constructor). Models with non-persistent learned parameters (`fitresult`) implement a modified model API that is documented [here](https://github.com/alan-turing-institute/MLJ.jl/blob/serialization-docs/docs/src/adding_models_for_general_use.md#serialization). The new user workflow will shortly appear in the [MLJ manual](https://alan-turing-institute.github.io/MLJ.jl/dev/) under "Machines". (https://github.com/JuliaAI/MLJSerialization.jl/issues/15, #733, https://github.com/JuliaAI/MLJSerialization.jl/issues/16) @olivierlabayle

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Improve display of `PerformanceEvaluation` objects (output of `evaluate/evaluate!`) to squeeze in measures with long names and multiple parameters (#757, https://github.com/alan-turing-institute/MLJ.jl/issues/923)
- (**enhancement**) Allow user to specify `scitype_check_level` when constructing machines, as in `machine(model, X, y, check_scitype_level=2)`, to control how strictly the constructor enforces scitype type compatibility between `model` and the data. Allow user to change the global default `scitype_check_level` using new method `scitype_check_level(i::Int)`.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Add a standard error column to the display of `PerformanceEvaluation` objects (as returned by `evaluate!`/`evaluate`) (#766) @rikhuijzer

**Comment by OkonSamuel** [comment]
@JuliaRegistrator register branch=master

release notes:

- bump compat for LossFunctions.jl dependency.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Support mulithreaded training of learning networks. Call as in `fit!(node, acceleration=CPUThreads())` (#785) @olivierlabayle 
- (**enhancement**) Create interface point for specifying `acceleration` mode when "exporting" a learning network as new model type, by supporting `acceleration` as keyword argument of `return!` method (#785) @olivierlabayle 
- (**enhancement**) Add `acceleration` and `cache` fields to `Stack` type (#785) @olivierlabayle

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Add support for feature importances (#798) @OkonSamuel

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Add support for model operations (such as `transform`) that return extra information for merging into machine reports (#806)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Add option in `make_regression` to generate multi-target data, as in `make_regression(100, 3, n_targets=2)` (#811) @josephsdavid

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Support `Static` models that have a `predict` or other operation implemented (in addition to `transform` already supported) #813

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master-0.19

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Introduce new protocol for exporting learning networks via the new family of supertypes  `*NetworkComposite` (#841, #831) 
- (**mildly breaking**) Remove key-value pairs from reports and fitted parameters that have `nothing` or `NamedTuple()` as a value. 
- (**breaking**) Re-implement `Stack`, `TransformedTargetModel` and pipelines (`Pipeline`) as `NetworkComposite` types. What is breaking is that some reports and fitted parameters will be missing some these keys: `machines`, `fitted_params_given_machine`, `report_given_machine`.  However, the only information contained in those items that is not rendered redundant by the existing items are considered private. 
- (**breaking**) Remove the formerly deprecated `@pipeline` macro, now rendered redundant by [`Pipeline`](https://alan-turing-institute.github.io/MLJ.jl/dev/linear_pipelines/) constructor (or `model1 |> model2 |> ... ` syntax) and  [`TransformedTargetModel`](https://alan-turing-institute.github.io/MLJ.jl/dev/target_transformations/#Target-Transformations).

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**bug fix**) #865 @OkonSamuel

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JulaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by juliohm** [comment]
@ablaom can you please trigger a new patch release?

**Comment by OkonSamuel** [comment]
> @ablaom can you please trigger a new patch release?

sure

**Comment by OkonSamuel** [comment]
> @OkonSamuel didn't see the patch yet. We are waiting for the patch to continue with updates downstream.

I'm working on it. I just bumped the MLJBase version.

**Comment by OkonSamuel** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Add hooks for MLflow integration (#925) @pebeto
- Make display of confusion matrices more space economic (#923) @Roeya

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**breaking**) Remove the definition of all measures (`mae`, `log_loss`, etc), which are instead to be be loaded from [StatisticalMeasures.jl](https://juliaai.github.io/StatisticalMeasures.jl/dev/). Remove completely measures previously corresponding to loss functions in LossFunctions.jl, which must now be explicitly imported and wrapped. For Julia < 1.9, make StatisticalMeasures a hard dependency and re-export it's names. For Julia 1.9 provide default measures for models using a Pkg extension, including StatisticalMeasures.jl as a weak dependency. See [this **migration guide**](https://github.com/alan-turing-institute/MLJ.jl/blob/measure/docs/src/performance_measures.md#migration-guide-for-changes-to-measures-in-mljbase-10) for dealing with these breaking changes. 

- (**breaking**) Remove the LossFunctions.jl dependency to close #570.

- Adapt the resampling (`evaluate!`) code (and a semi-duplication for model `Stack`s) to the new measure API set out in [StatisticalMeasuresBase.jl](https://juliaai.github.io/StatisticalMeasuresBase.jl/dev/). 

- (**breaking**) Remove deprecated `@pipeline` and `@from_network` macros (#932)

- (**breaking**) Remove target as alias for transformer in TransformedTargetModel (#933)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Arrange that calling `plot(mach)` on a machine `mach` calls `plot(mach.fitresult)`, allowing model implementations to define plot recipes locally and have them work on machines wrapping their models (#951)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Expose `feature_importances` in pipelines with a supporting supervised component, and in `TransformedTargetModel`s with supporting atomic model (#963)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**Performance enhancement**) Remove type instability for `predict(mach::Machine, ...)` in the easy and typical case that `mach` does not wrap a `Symbol` model (#969)

- (**New feature**) Give `evaluate` and `evaluate!` the option `compact=true`, to return  a `CompactPerformanceEvaluation` object with minimal memory footprint (#973)

- (**New feature**) Add an `InSample()` resampling strategy that trains and tests on the same data (whatever is specified by `rows`, or all supplied data) (#975)

- (**Display improvement**) Split the table displayed as part of an `PerformanceEvaluation` object over two tables, if needed, to deal with overly wide tables (#973)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancement**) Add facility to specify a logger globally,  with a setter `default_logger(logger)`, and a getter `default_logger()` (#979)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**enhancment**) Arrange that pipelines support transformers that need a target variable for training (#984)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Relax some restrictions on model types in `evaluate`/`evaluate!` (#985)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Drop support for Julia versions < 1.10.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

For the release notes:

- Allow tuples, in addition to vectors, when specifying `resampling=...` in `evaluate/evaluate!`, and fix a mistake in the error message for invalid `resampling` values (#1010)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Add support for CategoricalArrays 1.0 and CategoricalDistributions 0.2. This changes the behaviour of the re-exported methods `levels` and `unique`, as applied to `CategoricalArray` and `UnivariateFinite`. Whereas previously these returned a vector of "raw" values, they now return a `CategoricalVector`. See these CategoricalArrays.jl [release notes](https://github.com/JuliaData/CategoricalArrays.jl/releases/tag/v1.0.0).

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:
 
- (**enhancement**) Arrange that the objects returned by `evaluate/evaluate!` store the currently displayed "1.96SE" estimates of the radius of the confidence interval for each performance estimate, to be accessible via a new property `uncertainty_radius_95` (#1034)
- (**enhancement**) Allow users to specify a tag for a model or machine they are evaluating, as in `evaluate("my_model"=>model, ...)` in place of `evaluate(model, ...)`, to be accessible in the returned object via a new property, `tag`. Include the tag in the display of the returned object and vectors of the same (#1034)
- (**enhancement**) Allow users to pass a vector of (possibly tagged) models or machines in `evaluate/evaluate!` calls, as in `evaluate([model1, model2], ...)` or `evaluate(["knn with K=5"=>model1, "random forest"=>model2], ...)` (#1034).

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

(**new feature**) Add `describe` method (extended from DataAPI.jl) to give a short named tuple summary of a performance evaluation object, as output by `evaluate` or `evaluate!`. Useful for tabulating performance evaluations for multiple models. (#1045)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**new feature**) Add `Freezable` model wrapper: When `Freezable(model).frozen == true`, calling `fit!` on a machine bound to the wrapped model `Freezable(model)` is a no-op unless it has never been trained, even when new training rows are presented. Otherwise, the behaviour of `model` and `Freezable(model)` are the same. More generally, "freezability" applies to any model with `frozen` as a hyper-parameter (#1016).

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

There have been some changes to how objects returned by `evaluate` and `evaluate!` are displayed (with no changes to the API). The logic for how many significant digits to display is now handled by Measurements.jl (falling back to 3 significant digits if the uncertainty is `Inf` or `0.0`). And the uncertainties appearing under "1.96*SE" have been moved to the top table, next to the aggregated measurements. This resolves #1070 and #1068. Here's an example of the new display:

```
PerformanceEvaluation object with these fields:
  model, tag, measure, operation,
  measurement (per-fold aggregate), uncertainty_radius_95 (1.96*SE),
  per_fold, per_observation,
  fitted_params_per_fold, report_per_fold,
  train_test_rows, resampling, repeats
Tag: RandomForestClassifier-663
Extract:
┌───┬──────────────┬──────────────┬─────────────┬─────────┐
│   │ measure      │ operation    │ measurement │ 1.96*SE │
├───┼──────────────┼──────────────┼─────────────┼─────────┤
│ A │ Accuracy()   │ predict_mode │ 0.933       │ 0.053   │
│ B │ BrierScore() │ predict      │ -0.097      │ 0.064   │
└───┴──────────────┴──────────────┴─────────────┴─────────┘
┌───┬───────────────────────────────────────────────────────┐
│   │ per_fold                                              │
├───┼───────────────────────────────────────────────────────┤
│ A │ [1.0, 1.0, 0.92, 0.92, 0.92, 0.84]                    │
│ B │ [-0.00685, -0.000408, -0.141, -0.136, -0.138, -0.162] │
└───┴───────────────────────────────────────────────────────┘
Apply `describe` to this result for a named tuple summary.
```
