### ISSUE TITLE
For a 0.19 release

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBase.jl#665]
For merging onto [for-0-point-19-release branch](https://github.com/JuliaAI/MLJBase.jl/tree/for-0-point-19-release):

- [x] #664 
- [x] Add `TransformedTargetModel` (#678)
- [x] remove UnivariateFinite out (https://github.com/JuliaAI/MLJBase.jl/pull/688)
- [x] Allow nominal ranges consisting of different functions. #666
- [x] Modify unpack to return an extra value with all remaining columns (#691)
- [x] #677 
- [x] Remove deprecated code for exporting learning networks by hand (#643), which is now achieved using `return!` method ([docs](https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/#Method-II:-Finer-control-(advanced))). 
- [x] #694 
- [x] #696
- [x] Address some breaking changes to ScientificTypesBase 3.0, ScientificTypes 3.0, StatisticalTraits 2.0 **when these are released** #698
- [x] #697
- [x] #644 
- [x] Update MLJBase readme
- [x] (do this last) #695 

For inclusion in release notes in addition to above:

- (**enhancement**) Add a new parametric `Pipeline` type for constructing pipelines without macros. Pipelines are to be constructed using the syntax `model1 |> model2 |> ...` or with the constructor `Pipeline` which exposed more options. The `@pipeline` macro is deprecated (#664)
- (**enhancement**) Add the metamodel `TransformedTargetModel` for wrapping supervised models in transformations of the target variable, which can be *learned* transformations (eg, standardisation). Previously this functionality was available as part of `@pipeline` (#678)
- (**breaking**) The `|>` syntax is no longer available for creating learning networks as it is now reserved for pipeline creation and concatenation. Also, `model |> f` has a new meaning when `model` is a `Model` subtype or instance. Previously, it meant `f(model)`, but now it is syntactic sugar for `Pipeline(model, f)` (#664)
- (**breaking**) The `UnivariateFinite` distribution and constructor, and the `UnivariateFiniteArray` type, are no longer available, as they are now provided by a separate package [CategoricalDistributions.jl](https://github.com/JuliaAI/CategoricalDistributions.jl) (which includes generalization to signed and complex measures, and a better display) (#688)
- (**breaking**) `schema(X)` no longer includes the `nrows` property. Use `nrows(X)` instead. This follows from [changes](https://github.com/JuliaAI/ScientificTypes.jl/releases/tag/v3.0.0) in the dependency ScientificTypes.jl (#698)
- Progress meters are no longer displayed for processes concluding in 0.1 s or less (#698)
- (**mildly breaking**) To improve robustness, the `range(model, :hyperparameter, ...)` constructor now tries to infer type information for the range from the corresponding fieldtype for field `:hyperparameter`, rather than from the type of the current *value*. Fix a bug with the display. (#666)
- (**mildly breaking**) `unpack(table, p1, p2, ...)` now includes an extra component in its return value, namely a table with all columns not selected by any predicate `p1, p2, ... ` Generally existing code will just safely ignore the extra component (#691)
- (**breaking**) Because more plotting algorithms support it: #677. 
- (**breaking**) Remove deprecated code for exporting learning networks by hand (#643), which is now achieved using `return!` method ([docs](https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/#Method-II:-Finer-control-(advanced))). 
- (**enhancement**) The `partition` function can now be called with a tuple of data arguments, for "synchronised" partitioning, but this requires specifying `multi=true` (because some tables are tuples) as in `(Xtrain, ytrain), (Xtest, ytest) = partition((X, y), rng=123, multi=true)` #696
- (**mildly breaking**) Make the objects returned by `evaluate/evaluate!` into a `struct` (formerly a named tuple) and add informative doc-string (#697)
- (**enhancement**) #644 

Post-release:

- [ ] Review and merge https://github.com/JuliaAI/MLJModels.jl/pull/416, https://github.com/JuliaAI/MLJModels.jl/pull/417
- [ ] Review and merge https://github.com/JuliaAI/MLJEnsembles.jl/pull/13
- [ ] Review and merge https://github.com/JuliaAI/MLJTuning.jl/pull/160
- [ ] Update MLJ:
   - Manual 
   - binder example
- [ ] Update package dependency chart
- [ ] Update DataScienceTutorials.jl
- [ ] Update MLJTutorial.jl
- [ ] Update ablaom/HelloJulia.jl
- [ ] PR to update MLJ criticism at https://github.com/JuliaML/TableTransforms.jl
